### ISSUE TITLE
Error when uploading a module

### ISSUE THREAD

**Issue by tsaquet** [brianhks/nexus-puppet-forge-plugin#2]
Hello Brian,

I am very interested in your plugin, thank you for your work. Though, I have some troubles using it:

I work with Nexus 2.12.1-01.
I installed your plugin, I can see it in the module list.
I tried to updload this module: https://github.com/echoes-tech/puppet-wrappers which was previously compressed as tar.gz
On upload, I have this error: 

`2016-07-04 18:15:34,138+0200 ERROR [qtp1434012857-70] admin org.sonatype.nexus.puppetforge.EventsRouter - Error in puppet plugin event router
java.lang.NullPointerException: null
        at org.sonatype.nexus.puppetforge.EventsRouter.on(EventsRouter.java:193) ~[na:na]
        at sun.reflect.GeneratedMethodAccessor52.invoke(Unknown Source) ~[na:na]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.7.0_95]
...`

The tar.gz file is uploaded, but metadata.json is not extracted and pom file not created.

Can this be due to the difference of version? Is it something I did wrong?
Thank you!

Regards,
Thomas

**Comment by brianhks** [comment]
Is the metadata.json at the root of the tar file?

**Comment by tsaquet** [comment]
Hello,

Yes it is, in the tar file i have the exact content of the module https://github.com/echoes-tech/puppet-wrappers

Regards,
Thomas

**Comment by tsaquet** [comment]
Hello,

I reproduced the problem on a Nexus 2.11.4-01.
Here is the last file I tried to upload :

[wrappers.tar.gz](https://github.com/brianhks/nexus-puppet-forge-plugin/files/349997/wrappers.tar.gz)

Regards,
Thomas

**Comment by tsaquet** [comment]
Hello,

I'm still stuck with this problem, could you do something for me ? I really would like to use your module :)

Regards,
Thomas

**Comment by brianhks** [comment]
I used this project: https://github.com/brianhks/puppet-module-publisher to publish your module and it worked.

Download that project and modify the common.sh to point to your nexus server.
Create a modules folder and extract your module into a wrappers sub folder.  So your module will be in modules/wrappers

Then run ./publish_modules.sh "echoes-wrappers (0.8.0)"

It will compress and upload your module correctly.  Compare what it has done with what you were doing to find what the difference is.

Also note I've made changes to the plugin recently that make it more forge api compatible.
